lib/sax_parser.js
package.json
src/libxmljs.cc
src/xml_comment.cc
src/xml_element.cc
src/xml_node.cc

This updates nan to the latest and fixes some issues so that the module can work with the io.js 1.0.1 release.
Most changes are pretty trivial. sax_parser.js had to change the way it inherits from EventEmitter because the old way would cause an assertion trying to set up the ObjectWrap.

update nan to 1.5.1 and fix issues with the latest v8

---

src/xml_attribute.cc
src/xml_attribute.h
test/element.js

Proposal to #201 
This is useful to treat attribute with namespace.
Example:
```javascript
var libxmljs = require('./index.js');
var xml = '<root ' +
'xmlns:foo="http://www.example.com/fake/uri/foo"' +
'xmlns:bar="http://www.example.com/fake/uri/bar"' +
'>' +
'<node foo:attr="foo value" bar:attr="bar value" />' +
'</root>';
var doc = new libxmljs.parseXmlString(xml);
var node = doc.get('node');
var attrs = node.attrs();
attrs.forEach(function(attr) {
console.log(attr.namespace().prefix() + ':' + attr.name() + '="' + attr.value() + '"');
});
```
Output:
```
foo:attr="foo value"
bar:attr="bar value"
```

Add .namespace() to Attribute

---

index.js
src/libxmljs.cc

As @defunctzombie [requested](https://github.com/polotek/libxmljs/pull/302#issuecomment-106978992), I've extracted the feature-list from #300 so we can get this included independently. I'm not adding any tests to this, since I expect that we will be using this in other tests for threading pretty soon.

Bindings for list of features from xmlHasFeature

---

src/libxmljs.cc
src/xml_node.cc
src/xml_node.h
test/ref_integrity.js

This pull request causes XmlNodes to Ref() their parents. This causes the parent node's ref count to increase, which means that it won't be GC'ed until the ref count goes back down to 0. When the child node's destructor is called, it Unref()'s the parent node which decreases the parent ref count. This forces parent nodes to stick around while there are still children that haven't been freed.
This pull request also causes libxmljs to check that `xml_obj` hasn't been freed before it tries to access any of its properties. This mitigates segfaults caused by the XmlNode destructor accessing `xml_obj` properties. Though the parent Ref() part of this pull request already fixes most known segfault issues, this is still useful as an extra safety check to provide protection against undiscovered …

Segfault prevention/safety

---

.travis.yml

Do you want Travis to build against io.js?
The problem with `node-gyp` not working with iojs can be solved by using the version shipped with iojs, not the version from the latest npm we install separately.  See https://github.com/nodejs/io.js/issues/433 for details. So we update npm to latest upstream only for old versions of node.js, not for the current version or for iojs.

Get Travis to build for iojs as well

---

.travis.yml
package.json
src/libxmljs.cc
src/libxmljs.h
src/xml_attribute.cc
src/xml_attribute.h
src/xml_comment.cc
src/xml_comment.h
src/xml_document.cc
src/xml_document.h
src/xml_element.cc
src/xml_element.h
src/xml_namespace.cc
src/xml_namespace.h
src/xml_node.cc
src/xml_node.h
src/xml_sax_parser.cc
src/xml_sax_parser.h
src/xml_syntax_error.cc
src/xml_xpath_context.cc

Migration to Nan 2.0.x

---

src/libxmljs.cc
src/xml_namespace.cc
src/xml_namespace.h
test/ref_integrity.js

~XmlNamespace segfaults if the underlying xmlNs has been freed. Enhanced deregister node callback to prevent this from happening.

Prevent segfault when freeing namespace wrapper

---

index.js
lib/document.js
src/xml_document.cc
src/xml_document.h
test/document.js

This PR helps alleviate the issue of wanting to parse HTML fragments without them being wrapped in implied document elements (doctype, head, body, etc)

Document.fromHtmlFragment

---

src/xml_comment.cc
test/comment.js

We want to allow the creation of comments that you would expect to see for IE conditionals in HTML markup. For example:
```html
```
Should not escape the inner text of the comment. I can't think of a reason where escaping comment text *should* be necessary.

Comment nodes should not escape xml characters

---

index.js
src/libxmljs.cc
src/xml_document.cc
src/xml_document.h
src/xml_element.cc
src/xml_element.h
src/xml_namespace.cc
src/xml_node.cc
src/xml_node.h
test/document.js
test/element.js
test/memory_management.js
test/ref_integrity.js
test/z_memory_leak.js

Merge of #364 and #346: Fixes memory leaks and segfaults. Wrapped nodes maintain reference on nearest wrapped ancestor in order to reduce graph traversal required when destroying wrapper of node in detached graph.

Ref wrapped ancestor plus safe wrapper destruction

---

src/xml_element.cc
src/xml_element.h
src/xml_node.cc
src/xml_node.h
src/xml_text.cc
src/xml_text.h
test/element.js
test/text.js

Extracted from PR #359. Memory fixes when adding merge-able text nodes (implemented in #351) as children or siblings. Includes implementation of XmlText add-sibling methods (already in header). Duplication can be reduced when XmlElement and XmlText (and XmlComment) are refactored to share a base class where methods inappropriate to XmlNode (which is shared by XmlAttribute) can be located.

Fix text merge

---

src/xml_node.cc
src/xml_node.h
test/namespace.js

Fixes #270, replaces #271.
Replaces #271's `.nsDecls` API with `.namespaces(true)` (as suggested by @rc0x03 in https://github.com/polotek/libxmljs/pull/271#issuecomment-156881196), which only returns the namespaces that are locally defined on the target element.  Tested to ensure backward compatibility with existing code.
I will close #271, and refer to this PR.

.namespaces(local)

---

src/xml_node.cc

Adjust the forward declaration of get_wrapped_node_in_children
to avoid linker errors on some systems

Adjust a functions forward declaration to fix #367

---

src/xml_document.cc
test/html_parser.js

This commit adds [htmlParserOption](http://xmlsoft.org/html/libxml-parser.html#xmlParserOption) support and adds Document.toString() output configuration. The options for Document.toString() are now the same as Node.toString().
This pull request will fix #372 and #244

Added HTML doc toString and parse options

---

Makefile
src/xml_document.cc
test/fixtures/baseurl.dtd
test/xml_parser.js

This PR comprises two changes. I'll describe them as line comments below.
The main purpose of this PR is to add the baseUrl option to FromXml. I noticed that this (and a few other options) were already added to FromHtml a long time ago, so I added them to FromXml in the same way.
The two methods are almost identical, and probably should be refactored to move the common code into a separate function that they both call. If it had been done that way originally, then users of FromXml would have benefited from these extra options added to FromHtml.
So, some of the changes were just for the purposes of harmonizing the FromHtml and FromXml methods. I didn't want to factor out into a separate function, though -- it seemed like too big a change. In lieu of that, I just tried to get the two …

Baseurl for xml (as well as html)

---

.travis.yml
package.json

For the just-released node.js 6.0.0 there was also an update to nan, 2.3.2. This PR loosens the dependency on nan so that a 6-compatible version can be pulled in.

builds with node 6.0.0

---

vendor/libxml/Copyright

The the [libxml2 vendor subdirectory](https://github.com/libxmljs/libxmljs/tree/e1cea0583a383f34f65919758c5c2e92844c8b5f/vendor/libxml) of libxmljs does not contain the [upstream copyright notice](https://git.gnome.org/browse/libxml2/tree/Copyright?id=7e86eb5d4b1d3fa0e97a90661e098e641b4cde99) even though the MIT license wording states that
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software
as *the* sole condition of use. We should make sure to include them in the source repository, and in the sources as provided by the npm registry.

Include upstream copyright notice

---

README.md
appveyor.yml
lib/document.js
package.json
test/xml_parser.js
vendor/libxml/config.h

This pull request addresses issue #395 by uploading Windows binaries to GitHub Releases. If a user installs libxmljs on Windows, node-pre-gyp will use one of the precompiled binaries.
This also fixes issue #392 and adds AppVeyor CI testing for Windows builds.

Precompiled binary support

---

appveyor.yml
package.json
test/document.js

Adds AppVeyor build support for Node version 6 and 7.
@defunctzombie @polotek All you have to do is bump the version with a tagged commit, publish to NPM, and libxmljs users can start using Windows binaries. 🎈🎉

Windows builds for Node 6 & 7

---

appveyor.yml
package.json

More binary support for Windows.

New build archs, deploy as tar.gz, always use MSVS 2015

---

package.json

Upgrade NAN to version 2.5 and allow the use of newer patch versions.
This is not a regression back to [the last time we allowed newer NAN versions](https://github.com/libxmljs/libxmljs/commit/70dd1d6c1504a1831f8a2deb78f40da6dc82c128).
We were allowing minor version bumps of NAN, which caused problems. Allowing patch versions can't hurt since NAN [follows semver](https://github.com/nodejs/nan/issues/215).

Bump NAN to v2.5.x

---

appveyor.yml
package.json

- remove node `0.10` and `0.12`
- add node 9, 10.
- downgrade `node-pre-gyp` to `0.6.37`
- use `~` for version to accept only patch update
i dont know what's the last good version of `node-pre-gyp` so i'm just going to use one in release `0.18.7`
Fixes: #509 #506

Fix appveyor build

---

binding.gyp
index.js
lib/element.js
lib/pi.js
src/xml_node.cc
src/xml_pi.cc
src/xml_pi.h
test/pi.js

Added a bridge to `xmlNewDocPI` for the ability of inserting and manipulating xml processing instructions. 
Closes #515
Adds a new `ProcessingInstruction` top level export class, which shares most of its implementation with the `Comment` class. The only difference is that the ProcessingInstruction also has a `name` attribute
Usage examples:
1) Adds a processing instruction before the root node
```js
const libxmljs = require('libxmljs');
var xml =  '<?xml version="1.0" encoding="UTF-8"?>' +
'<root>' +
'<child foo="bar">' +
'<grandchild baz="fizbuzz">grandchild content</grandchild>' +
'</child>' +
'<sibling>with content!</sibling>' +
'</root>';
var xmlDoc = libxmljs.parseXml(xml);
var pi = libxmljs.ProcessingInstruction(xmlDoc, 'mypi', 'mycontent');
xmlDoc.root().addPrevSibling(pi); …
```

Add libxml2 processing instructions support

---

binding.gyp

This fixes the build on Node 16 on Macs. It works in my limited testing, but someone who knows more about this needs to sanity check the solution.
This aims to solve the following issue: https://github.com/libxmljs/libxmljs/issues/592

Adjust the version of the c++ standard libraries used to build on Mac.

---

src/xml_document.cc
test/html_parser.js

Need to specify the encoding as `HTML` to fix #398 
(See http://xmlsoft.org/encoding.html#Default)
This PR adds the ability to provide a `encoding` option to `toString()`.

Added encoding for toString() method

---

lib/api.ts
test/document.ts

`Document.fromXmlAsync` calls `fromHtmlAsync` instead of delegating to the proper `fromXmlAsync`.
This PR fixes the function declaration (which wrongly refers to `HTMLParseOptions`) and the implementation and adds a test for it.
Fixes #618

Fix Document.fromXmlAsync

---

.npmignore

This change reduces the size of the package from 5.6MB (42MB unpacked) to 2.4MB (17.4MB unpacked).
This was tested to not break #614 by building the package with `npm pack` and then installing it in a different (dummy) project with `npm install --build-from-source /path/to/libxmljs-1.0.6.tgz`.
Fixes #616

Reduce size of tgz by excluding parts of vendor we don't need

---

lib/document.ts
lib/parse.ts
test/xml_parser.ts

The options that were passed to the `parseXmlAsync` method were not used to create the correct flags.
The XML or HTML options were not being processed in the parseBufferAsync method as they were in the `parseXml` or `parseHtml` methods.
Added a new method that resolves the options by the `FROM_BUFFER_ASYNC_TYPE`.

Fix resolving flags in the parseBufferAsync method

---

.github/workflows/test-deploy.yml

This PR adds build steps for node 20.
It also contains the followin changes:
1. Splits the macos and windows builds since the MAC build didn't like the `npm config set msvs_version "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --global` argument into npm.
2. Removes the "invalid"? npm config command `npm config set spin false` which no longer is supported in newer NPM versions.
3. Adds builds steps arm64 macos

chore: add build steps for node 20

---

.github/workflows/test-deploy.yml
package.json

Hi @rchipka @anderssonoscar0 
this PR in order to fix https://github.com/libxmljs/libxmljs/issues/637 (basically removed darwin arm64 build)
Today the crossbuild darwin x64_86 -> arm64 seems not to be supported on standard x86_64 macos runners, thus the supposed arm64 artefact (https://github.com/libxmljs/libxmljs/releases/download/v1.0.10/node-v115-darwin-arm64.tar.gz) contains a x86_64 file, and this one is not usable on a M1/M2 cpu.
An option would be to use a recently released github silicon worker (https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) but they are not available for free by contrast to standard macos runners.
That's why I suggest to remove this build for now.

Fix ci darwin arm64

---

lib/parse.ts
test/xml_parser.ts

We're currently using `libxmljs` to parse XML for SAML IDP metadata. When we fetch the metadata from the service, the `response.body` may sometimes come back as a string with the following invisible first character: `\uFEFF`.
This character is the Unicode Byte Order Mark (BOM). It’s a special invisible character that's often used at the beginning of text files to indicate the byte order (endianness) of the file, and it is particularly common for UTF-8 encoded files.
I noticed that the behavior between `libxmljs.parseXml` and `libxmljs.parseXmlAsync` handled this invisible character differently. 
`libxmljs.parseXml` succeeds with no issue because if the `buffer` is a `string`, it will default to an encoding of `UTF-8`.
However, `libxmljs.parseXmlAsync` fails because it only uses …

fix: make parseXMLAsync and parseXML have the same defaults for encoding

---

.github/workflows/test-merge.yml
lib/api.ts
lib/document.ts
lib/index.ts
lib/parse.ts
lib/schema.ts

Proposal for #628.
The goal is to provide a way to validate multiples docs without parsing again the schema.
```typescript
import libxmljs from "libxmljs";
const xsd = '<?xml version="1.0" encoding="UTF-8"?>...'
// Parse schema and build context
const schema = libxmljs.parseSchema(xsd)
// Validate all docs
schema.validateDocument(xmlDoc1)
schema.validateDocument(xmlDoc2)
schema.validateDocument(xmlDoc3)
// Still working
xmlDoc1.validate(xsd)
```

Validate multiple doc without rebuilding schema
